### ISSUE TITLE
Rlkit/multiworld not found error after successful installation

### ISSUE THREAD

**Issue by shivanimall** [martius-lab/SMORL#1]
I followed the steps on the README.md, and get the following error after successfully installing. 
running smoke_test/gt_rearrange_x.py from inside the rlkit/multiworld dir works fine however for their specific module loadings. is this a path issue?
```
(smorl2) Nityas-Macbook-Pro:SMORL shivanimall$ pip install -e ./multiworld
Obtaining file:///Users/shivanimall/SMORL/multiworld
Installing collected packages: multiworld
  Running setup.py develop for multiworld
Successfully installed multiworld

(smorl2)Macbook-Pro:SMORL shivanimall$ pip install -e ./rlkit
Obtaining file:///Users/shivanimall/SMORL/rlkit
Installing collected packages: rlkit
  Running setup.py develop for rlkit
Successfully installed rlkit

(smorl2)Macbook-Pro:SMORL shivanimall$ python -W ignore  rlkit/settings/smorl/smoke_test.py
Traceback (most recent call last):
  File "/Users/shivanimall/SMORL/rlkit/settings/smorl/smoke_test.py", line 6, in <module>
    import rlkit.util.hyperparameter as hyp
ModuleNotFoundError: No module named 'rlkit'
```
```
(smorl2) Nityas-Macbook-Pro:SMORL shivanimall$ python gt_rearrange_3_object.py 
Traceback (most recent call last):
  File "/Users/shivanimall/SMORL/gt_rearrange_3_object.py", line 5, in <module>
    from multiworld.envs.mujoco.cameras import sawyer_init_camera_zoomed_in
ModuleNotFoundError: No module named 'multiworld.envs'
```

**Comment by shivanimall** [comment]
I also had to comment out last line in rlkit/setup.py since it gave me the following error:

```
(smorl2)Macbook-Pro:SMORL shivanimall$ pip install -e ./rlkit
Obtaining file:///Users/shivanimall/SMORL/rlkit
    ERROR: Command errored out with exit status 1:
     command: /Users/shivanimall/anaconda3/envs/smorl2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/shivanimall/SMORL/rlkit/setup.py'"'"'; __file__='"'"'/Users/shivanimall/SMORL/rlkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fd/5jk_ll1j7gzbjtr57ltsdtww0000gn/T/pip-pip-egg-info-ixuhus44
         cwd: /Users/shivanimall/SMORL/rlkit/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/shivanimall/SMORL/rlkit/setup.py", line 9, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by zadaianchuk** [comment]
Can you try to install from the conda environment using 
`python -m pip install -e ./rlkit`?

**Comment by shivanimall** [comment]
yes, that worked, thanks.
